title: Board & Officers
description: Ongoing projects at All Hands Active

# not really an author, but it should work for us
author: This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.

theme: minima
